* 
:properties:
:author: Dr. Y. V. Lokeswari
:date: 24-May-2022
:end:

#+startup: showall

{{{title-tab}}}
| CODE | COURSE TITLE               | L | T | P | C |
|      | PRINCIPLES OF DATA SCIENCE | 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
- To learn fundamentals of Data Science using Python.
- To develop python program for analysis of data using Python libraries.
- To develop python programs for manipulating and visualizing the data.
- To understand probability and Statistics for the data.
- To be familiar with supervised and unsupervised methods in machine learning.
** After BoS Meeting
- To be familiar with real time applications in data science.


{{{unit}}}
| UNIT I | INTRODUCTION TO DATA SCIENCE | 9 |
Introduction: Need for data science -- Benefits and uses -- Causality and Experimentation -- Facets of data-Data science process: Retrieving data -- Cleansing, integrating and transforming data -- Exploratory Data Analysis -- Build the models -- Presenting findings and building applications.

{{{unit}}}
|UNIT II|PYTHON LIBRARIES FOR DATA SCIENCE |9| 
NumPy Basics: Arrays and Vectorized Computation -- The NumPy ndarray -- Creating ndarrays -- Data Types for ndarrays -- Arithmetic with NumPy Arrays -- Basic Indexing and Slicing -- Boolean Indexing -- Transposing Arrays and Swapping Axes. Introduction to pandas Data Structures: Series, DataFrame -- Essential Functionality: Dropping Entries -- Indexing, Selection, and Filtering -- Function Application and Mapping- Sorting and Ranking. Summarizing and Computing Descriptive Statistics -- Unique Values, Value Counts, and Membership. Reading and Writing Data in Text Format.

{{{unit}}}
|UNIT III|DATA CLEANING, PREPARATION AND VISUALIZATION |9| 
Data Cleaning and Preparation: Handling Missing Data -- Data Transformation: Removing Duplicates, Transforming Data Using a Function or Mapping, Replacing Values, Detecting and Filtering Outliers- String Manipulation: Vectorized String Functions in pandas. Plotting with pandas and matplotlib: Line Plots, Bar Plots, Histograms and Density Plots, Scatter or Point Plots.

{{{unit}}}
|UNIT IV|STATISTICAL ANALYSIS |9| 
Introduction -- Data Preparation -- Exploratory Data Analysis: Data summarization -- Data distribution -- Outlier Treatment -- Measuring asymmetry -- Continuous distribution -- Empirical Distribution; Estimation: Mean -- Variance -- Randomness -- Sampling -- Covariance -- Correlation, Measuring the Variability in Estimates: Point estimates -- Confidence intervals; Hypothesis Testing: Using confidence intervals -- Using p-values


{{{unit}}}
|UNIT V|PREDICTION AND INFERENCE WITH MACHINE LEARNING |9|
Machine learning -- Modeling Process -- Training model -- Validating model -- Predicting new observations -- Supervised learning algorithms -- Linear Regression -- Unsupervised learning algorithms -- K Means Clustering -- Reinforcement learning.

** After BoS meeting.
{{{unit}}}
|UNIT V| BUSINESS APPLICATIONS WITH DATA SCIENCE |9|
Machine learning -- Supervised learning algorithms -- Linear Regression -- Unsupervised learning algorithms -- K Means Clustering -- Reinforcement learning. Case Studies: Customer analytics in the retail industry -- Recommendation systems in marketing & advertising -- Sales analytics -- Predictive analytics in healthcare -- Weather predictions in agriculture sector.

\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to
1. Demonstrate the need and the fundamental concepts of data science. (K2)
2. Develop Python programs to perform analysis on data using Python libraries. (K3)
3. Develop Python programs for data preparation and visualizing the data. (K3)
4. Interpret the various statistical inferences (K2)
5. Develop applications to demonstrate data analysis in practice (K3)

      
** REFERENCE BOOKS
1. Davy Cielen, Arno D B Meysman, Mohamed Ali, ``Introducing Data Science - Big data, Machine Learning, and more using Python tools'', Manning Publications Co, 2016. (Unit I)
2. Wes McKinney, ``Python for Data Analysis: Data Wrangling with Pandas, NumPy, and IPython'', O'Reilly, 2nd Edition,2018. (Unit II & III)
3. Laura Igual, Santi Segua, ``Introduction to Data Science - A Python Approach to Concepts, Techniques and Applications'', Springer Nature, 2017 (Unit IV & V)
4. AniAdhikari, JohnDeNero,``Computational and Inferential Thinking: The Foundations of Data Science'', GitBook, 2017. (Unit I & IV).
5. Jake VanderPlas, ``Python Data Science Handbook: ``Essential Tools for Working with Data'', O'Reilly Media, 2016.
6. Foster Provost, Tom Fawcett, ``Data Science for Business'', O'Reilly Media, 2013
7. Rachel Schutt, Cathy O'Neil, ``Doing Data Science'', O'Reilly Media, 2016
