* 
:properties:
:author: S Kavitha
:date: 10 May 2022
:end:

#+startup: showall
{{{title-tab}}}
| CODE | COURSE TITLE                 | L | T | P | C |
|      | RESEARCH METHODOLOGY AND IPR | 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
- To impart knowledge on research design, data collection and preparation
- To develop skills on data analysis and technical paper writing / presentation without violating professional ethics 
- To understand the importance of Intellectual Property Rights and its development process
- To understand the process of Patent drafting and filing 

{{{unit}}}
|UNIT I |RESEARCH DESIGN |6|
Overview of research process and design; Use of Secondary and exploratory data to answer the research question; 
Qualitative research; Observation studies; Experiments and Surveys. 

{{{unit}}}
|UNIT II| DATA COLLECTION AND SOURCES |6| 
Measurements: Measurement Scales; Questionnaires and Instruments; Sampling and methods.
Data-Preparing -- Exploring -- examining and displaying. 

{{{unit}}}
|UNIT III| DATA ANALYSIS AND REPORTING |6| 
Overview of Multivariate analysis; Hypotheses testing and Measures of Association; 
Presenting Insights and findings using written reports and oral presentation. 

{{{unit}}}
|UNIT IV| INTELLECTUAL PROPERTY RIGHTS |6| 
Intellectual Property: The concept of IPR -- Evolution and development of concept of IPR -- IPR development process: Trade secrets -- utility Models -- 
Right of Property; Common rules of IPR practices; Types and Features of IPR Agreement; Trademark.

#+begin_comment
IPR & Biodiversity, Role of WIPO and WTO in IPR establishments, Functions of UNESCO in IPR maintenance.
are removed 
#+end_comment

{{{unit}}}
|UNIT V| PATENTS |6|
Patents: objectives and benefits of patent; Concept, features of patent; Inventive step; Specification; Types of patent application; process E-filing; 
Examination of patent; Grant of patent; Revocation; Equitable Assignments; Licences, Licensing of related patents. 

#+begin_comment
patent agents, Registration of patent agents are removed
#+end_comment

\hfill *Total Periods: 30*

** COURSE OUTCOMES
On successful completion of this course, the student will be able to
- Interpret and formulate a research problem (K2)
- Develop corpus to carry out research analysis (K3)
- Develop skills on data analysis, report writing and presentation (K3)
- Infer the basic knowledge of IPR (K2)
- Explain the importance of patents and understand the patenting process (K2)

** REFERENCES
1. Cooper Donald R and Schindler Pamela S, ``Business Research Methods'', Tata McGraw Hill Education, 12 edition, 2014.
2. Catherine J. Holland, ``Intellectual property: Patents, Trademarks, Copyrights, Trade Secrets'', Entrepreneur Press, 2007. 
3. David Hunt, Long Nguyen, Matthew Rodgers, ``Patent searching: tools & techniques'', Wiley, 2007. 

#+begin_comment
Removed one book 
#+end_comment

