:properties:
:author: S Kavitha
:date: 10 May 2022
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 2 | 0 | 0 | 2 |

** Course Objectives
To impart knowledge and skills required for research and IPR: 
- Problem formulation, analysis and solutions. 
- Technical paper writing / presentation without violating professional ethics 
- Patent drafting and filing patents


{{{unit}}}
|Unit I |Research Design |6|
Overview of research process and design; Use of Secondary and exploratory data to answer the research question; Qualitative research; Observation studies; Experiments and Surveys. 

{{{unit}}}
|Unit II| Data Collection and Sources |6| 
Measurements: Measurement Scales; Questionnaires and Instruments; Sampling and methods.
Data-Preparing -- Exploring -- examining and displaying. 

{{{unit}}}
|Unit III| Data Analysis and Reporting |6| 
Overview of Multivariate analysis; Hypotheses testing and Measures of Association; 
Presenting Insights and findings using written reports and oral presentation. 

{{{unit}}}
|Unit IV| Intellectual Property Rights |6| 
Intellectual Property: The concept of IPR -- Evolution and development of concept of IPR -- IPR development process: Trade secrets -- utility Models -- Right of Property; Common rules of IPR practices; Types and Features of IPR Agreement; Trademark.

#+begin_comment
IPR & Biodiversity, Role of WIPO and WTO in IPR establishments, Functions of UNESCO in IPR maintenance.
are removed 
#+end_comment

{{{unit}}}
|Unit V| Patents |6|
Patents: objectives and benefits of patent; Concept, features of patent; Inventive step; Specification; Types of patent application; process E-filing; Examination of patent; Grant of patent; Revocation; Equitable Assignments; Licences, Licensing of related patents. 

#+begin_comment
patent agents, Registration of patent agents are removed
#+end_comment

\hfill *Total: 30*

** Course Outcomes
On successful completion of this course, the student will be able to
- Interpret and formulate research problem (K2)
- Develop data to carry out research analysis (K3)
- Develop skilss on report writing and presentation (K)
- Infer the basic knowledge of IPR (K2)
- Summarize the iportance of patent and its process (K2)

** References
1. Cooper Donald R and Schindler Pamela S, “Business Research Methods”, Tata McGraw Hill Education, 12 edition, 2014.
2. Catherine J. Holland, “Intellectual property: Patents, Trademarks, Copyrights, Trade Secrets”, Entrepreneur Press, 2007. 
3. David Hunt, Long Nguyen, Matthew Rodgers, “Patent searching: tools & techniques”, Wiley, 2007. 

#+begin_comment
Removed one book 
#+end_comment


#+begin_comment  
** CO PO MAPPING 
#+NAME: co-po-mapping
|                |    |PO1 | PO2 | PO3 | PO4 | PO5 | PO6 | PO7 | PO8 | PO9 | PO10 | PO11 | 
|                |    | K3 | K6  |  K6 |  K6 | K6  |     |     |     |     |      |      |     
| CO1            | K2 |  2 |     |     |     |     |     |     |     |     |      |   2  |    
| CO2            | K4 |  3 |  2  |  2  |  2  |  2  |     |     |     |     |      |      |  
| CO3            | K3 |  3 |  2  |  2  |  2  |  2  |     |     |     |     |      |      |    
| CO4            | K3 |  3 |  2  |  2  |  2  |  2  |     |     |     |     |      |      |    
| CO5            | K2 |  2 |     |     |     |     |     |     |     |     |      |      |    
| Total          |    | 13 |  6  |  6  |  6  |  6  |     |     |     |     |      |   2  |   
| Course Mapping |    |  3 |  2  |  2  |  2  |  2  |     |     |     |     |      |   2  | 
#+end_comment
