* 
:properties:
:author: Dr. Y. V. Lokeswari
:date: 03-June-2022
:end:

#+startup: showall
{{{title-tab}}} 
| CODE | COURSE TITLE     | L | T | P | C |
|      | DATA SCIENCE LAB | 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
- To get familiar with the python programming for data science
- To develop python programs for data preparation and manipulation using NumPy and Pandas.
- To construct python programs for data visualization
- To make use of python packages for statistical analysis
- To apply business analytics on real world applications.


** SUGGESTIVE EXPERIMENTS
1. Implement basic data types and user defined functions using Python.
2. Develop python programs for packages and working on files.
3. Perform basic computations and manipulation on arrays using NumPy package.
4. Perform manipulations on the CSV files and images using NumPy package.
5. Perform data manipulation on the input CSV file using Pandas Package.
6. Perform data preparation and visualization on the input CSV file using Pandas matplotlib pacakages.
7. Perform Exploratory Data Analysis on a CSV file.Import any CSV file and perform Exploratory Data Analysis: Data summarization.
8. Compute the following for the given data set using NumPy package. Compute Mean, Variance, Standard Deviation, Sampling, Covariance, Correlation.
9. Download data from UCI Machine Learning Repository and perform the supervised learning algorithm. Implement the Linear Regression for the given application.
10. Download data from UCI Machine Learning Repository and perform the unsupervised learning algorithm. Implement the K Means Clustering algorithm for the given application.

** After BoS Meeting
9.	Download data from UCI Machine Learning Repository or Kaggle and perform the business analytics for the application “Predictive analytics in healthcare”.
10.	Download data from UCI Machine Learning Repository or Kaggle and perform the business analytics for the application “Weather predictions in agriculture sector”.


\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
1. Analyze the significance of python packages for data creation and manipulation (K4)
2. Experiment the methods of data handling and visualization through NumPy, Pandas and MatplotLib modules (K3).
3. Construct Python programs for obtaining statistical inference on data and apply business analytics for the real world applications. (K3)
