* 
:Properties:
:author:  B Senthil Kumar, D Thenmozhi
:date: 11 May 2022
:end:

#+startup: showall
{{{title-tab}}}
| CODE | COURSE TITLE                | L | T | P | C |
|      | NATURAL LANGUAGE PROCESSING | 2 | 0 | 2 | 3 |


** COURSE OBJECTIVES
- To learn the fundamentals in language processing.
- To understand  syntactic parsing in language processing.
- To understand language modeling using vector semantics.
- To understand  semantics of words and sentences in languages.
- To understand  information extraction techniques.

{{{unit}}}
|UNIT I |INTRODUCTION|6| 
Knowledge in language processing -- Ambiguity; Text Normalization -- N-grams -- Evaluation -- Sampling -- 
Generalization -- Smoothing


{{{unit}}}
|UNIT II|WORD LEVEL AND SYNTACTIC ANALYSIS |6| 
English Word Classes -- Part-of-Speech Tagging; Constituency Grammar: Context-Free Grammar -- 
Grammar rules for Engligh -- Treebanks; Dependency Parsing: Dependency Relations -- Formalisms -- 
Dependency Treebanks;


{{{unit}}}
|UNIT III|LEXICAL AND VECTOR SEMANTICS|6|
Lexical Semantics -- Vector Semantics -- Words and vectors -- Cosine similarity -- TF-IDF -- PPMI -- Word2Vec -- Semantic properties of embeddings -- Evaluating vector model; 


{{{unit}}}
|UNIT IV|SEMANTIC ANALYSIS|6|
Word Senses: Senses Relations -- WordNet -- Word Sense Disambiguation; Semantic Roles: Diathesis Alternations 
-- Problems -- Proposition Bank -- Semantic Role Labeling

{{{unit}}}
|UNIT V|INFORMATION EXTRACTION AND COREFERENCE|6|
Named Entities -- Named Entity Tagging; Relation Extraction -- Algorithms -- Extracing Times 
-- Extracting Events and their Times -- Template Filling; Coreference:Linguistic Background -- Tasks
and Datasets;


\hfill *Periods: 30*
 
**  SUGGESTED EXERCISES
1. Apply Tokenizer, n-grams in text normalization.
2. Apply TF-IDF, Word2Vec vectors for the given text data for word similarity.
3. Generate the PoS tag for the input sentence.
4. Apply treebanks for context-free and dependency parsing.
5. Apply the WordNet to find the lexical similarity.
6. Apply semantics to find the word sense/SRL.
7. Apply IE techniques to extract the Named Entities/Relations.

 
\hfill *Periods: 30*

\hfill *Total Periods: 60*


** COURSE OUTCOMES
After the completion of this course, students will be able to: 
1. Apply the text normalization techniques. (K3)
2. Apply syntactic analysis in language processing (K3)
3. Apply vector semantics for word embeddings. (K3)
4. Apply semantic analysis for words and sentences. (K3)
5. Apply extraction techniques to extract the information. (K3)


** REFERENCES
1. Daniel Jurafsky and James H Martin, ``Speech and Language Processing: An introduction to Natural Language Processing, Computational Linguistics and Speech Recognition'',3rd Edition
2. Christopher D. Manning, Hinrich Schutze, Foundations of Statistical Natural Language Processing, MIT Press, 1999.
3. Steven Bird, Ewan Klein, and Edward Loper, ``Natural Language Processing with Python'', O'Reilly, 2009.
4. Tanveer Siddiqui, U.S. Tiwary, ``Natural Language Processing and Information Retrieval'', Oxford University Press, 2008.
5. Nitin Indurkhya, Fred J. Damerau, Handbook of Natural Language Processing, 2nd Edition, CRC Press, 2010.
