* 
:properties:
:author: V.S.Felix Enigo
:date: 31 May 2022
:end:

#+startup: showall
{{{title-tab}}}
| CODE | COURSE TITLE               | L | T | P | C |
|      | ADVANCED COMPUTER NETWORKS | 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
- To study the network fundamentals. 
- To study the 5G network functional architecture
- To study about 2G and 4G cellular networks. 
- To understand and build software defined networks. 

{{{unit}}}
| UNIT I | NETWORK FUNDAMENTALS | 7 |
Introduction -- Networking Hardware -- Network Cabling -- Wireless Networking -- IP addressing -- Protocols -- Internet.

{{{unit}}}
| UNIT II | CELLULAR NETWORKS | 9 |
GSM -- Mobility management and call control -- GPRS -- GPRS State model -- Network elements -- Mobility management and session management -- Small Screen Web Browsing over GPRS and EDGE -- MMS over GPRS.

{{{unit}}}
| UNIT III | 4G NETWORKS | 9 |
LTE -- Network architecture and interfaces -- Mobility management and power optimization -- LTE security architecture -- Interconnection with UMTS and GSM -- 4G networks and composite radio environment -- Protocol boosters -- Hybrid 4G wireless networks protocols.

{{{unit}}}
| UNIT IV | 5G NETWORKS | 10 |
Use cases and requirements –- 5G system concepts –- 5G Architecture: NFV and SDN -- Basics about RAN architecture -- High-level requirements -- Functional architecture and 5G flexibility: Functional split criteria -- Functional split alternatives -- Functional optimization for specific applications -- Integration of LTE and new air interface to fulfill 5G Requirements -- Enhanced Multi-RAT coordination features -- Physical architecture and 5G deployment.

{{{unit}}}
| UNIT V | SOFTWARE DEFINED NETWORKS | 10 |
Introduction -- Centralized and distributed control and data planes -- Open flow -- Wire protocol -- Architecture -- Hybrid approaches - SDN controllers -- Building SDN using Emulator.


\hfill *Total Periods: 45*
  
** COURSE OUTCOMES
After the completion of this course, students will be able to: 
1. Explain the fundamentals of networking (K2).
2. Analyse the working of GSM network (K4)
3. Analyse the use of various 4G Networks (K4).
4. Explain the functional architecture of 5G networks (K2)
5. Build software defined networks using an emulator (K3). 

** REFERENCES
1. James Bernstein, ``Networking made Easy'', 2018. (Unit - I) 
2. Martin Sauter, ``From GSM to LTE, An Introduction to Mobile Networks and Mobile Broadband'', Wiley, 2014.(Unit - II, III)
3. Savo G Glisic, ``Advanced Wireless Networks -- 4G Technologies'', John Wiley & Sons, 2007. (Unit - III)
4. Afif Osseiran, Jose F. Monserrat, Patrick Marsch, ``5G Mobile and Wireless Communications Technology'', Cambridge University Press Second Edition 2011. (Unit – IV)
5. Thomas D. Nadeau and Ken Gray, ``SDN -- Software Defined Networks'', O'Reilly Publishers, 2013.  (Unit - V)
