* <<<CP1221>>> CLOUD COMPUTING
:properties:
:author: N Sujaudeen
:date: 12 May 2022
:end:

#+startup: showall

#+begin_comment

** CO PO MAPPING 
#+NAME: co-po-mapping
|                |    |PO1 | PO2 | PO3 | PO4 | PO5 | PO6 | PO7 | PO8 | PO9 | PO10 | PO11 | 
|                |    | K3 | K6  |  K6 |  K6 | K6  |     |     |     |     |      |      |     
| CO1            | K2 |  2 |     |     |     |     |     |     |     |     |      |      |    
| CO2            | K3 |  3 |     |     |     |     |     |     |     |     |      |      |  
| CO3            | K3 |  3 |     |     |  2  |  2  |     |     |     |     |      |      |    
| CO4            | K3 |  3 |  2  |     |  2  |  2  |     |     |     |     |      |      |    
| CO5            | K2 |  2 |     |     |     |     |     |     |     |     |      |      |    
| Total          |    | 13 |  2  |     |  4  |  4  |     |     |     |     |      |      |   
| Course Mapping |    |  3 |  2  |     |  2  |  2  |     |     |     |     |      |      |  

#+end_comment

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** Course Objectives
- To understand the principles of Cloud Architecture, Models and Infrastructure.
- To understand the concepts of virtualization and virtual machines.
- To gain knowledge about virtualization Infrastructure.
- To explore and experiment various Cloud deployment environments.
- To learn about the security issues in the cloud environment. 

{{{unit}}}
| Unit I | Cloud Architecture Models and Infrastructure | 9 |
Cloud Architecture: System Models for Distributed and Cloud Computing
-- NIST Cloud Computing Reference Architecture -- Cloud deployment
models -- Cloud service models; Cloud Infrastructure: Architectural
Design of Compute and Storage Clouds -- Layered Cloud Architecture
Development -- Design Challenges -- Inter Cloud Resource Management --
Resource Provisioning and Platform Deployment -- Global Exchange of
Cloud Resources.
#+latex: % Unit III is from the course Cloud Computing IF7202, Anna University. M.E CSE - R2015 (NS)


{{{unit}}}
| Unit II | Virtualization | 9 |
Basics of Virtualization -- Emulation -- Interpretation -- Binary
Translation -- Virtualization Advantages -- Virtual Machine Basics --
Taxonomy of Virtual Machines -- Process Virtual Machines -- System
Virtual Machines -- Hypervisor -- Key Concepts -- Virtualization
structure -- Implementation levels of virtualization -- Virtualization
Types: Full Virtualization -- Para Virtualization -- Hardware
Virtulization.
#+latex: % Unit I is from the course Virtualization IF7020, Anna University. M.Tech IT- R2015 (NS)

{{{unit}}}
| Unit III | Virtualization Infrastructure | 9 |
Comprehensive Analysis -- Resource Pool -- Testing Environment --
Virtual Workloads -- Provision Virtual Machines -- Desktop
Virtualization -- Network Virtualization -- Server and Machine
Virtualization -- Storage Virtualization -- System-level of Operating
Virtualization -- Application Virtualization-- Virtualization of CPU,
Memory and I/O devices -- Virtual clusters and Resource Management --
Virtual Machine Monitors: KVM, Xen, VMWareESXi server.
#+latex: % Unit II is from the course Virtualization IF7020, Anna University. M.Tech IT- R2015 (YVL)

{{{unit}}}
| Unit IV | Cloud Deployment Environment | 9 |
Google App Engine -- Amazon AWS -- Microsoft Azure; Cloud Software
Environments -- Eucalyptus -- OpenStack -- OpenNebula -- Aneka --
CloudSim.
#+BEGIN_COMMENT
Unit IV is from the course Cloud Computing IF7202, Anna University. M.E CSE - R2015. 
Apache Hadoop is not  included here, as it will be covered in Big Data Analytics course. (YVL)
#+END_COMMENT

{{{unit}}}
| Unit V | Cloud Security | 9 |
Multi-tenancy Issues: Isolation of users/VMs from each other --
Virtualization System Vulnerabilities: Management console
vulnerabilities -- management server vulnerabilities -- administrative
VM vulnerabilities -- guest VM vulnerabilities, hypervisor
vulnerabilities -- hypervisor escape vulnerabilities -- configuration
issues; Virtualization System-Specific Attacks: Guest hopping --
VM migration attack -- hyperjacking.
Data Security and Storage; Identity and Access Management(IAM) - IAM Challenges - IAM Architecture and Practice.
#+latex: % As we changed entire Unit - V from AU syllabus, Unit V is from the course Cloud Security CC2005, SRM University. M.Tech in Cloud Computing. (YVL) 

\hfill *Total: 45*

** Course Outcomes 
After the completion of this course, students will be able to: 
- Describe the design challenges in cloud (K2)
- Apply the concept of virtualization and its types (K3)
- Experiment with virtualization of hardware resources and Virtual Machine Monitors (K3)
- Develop and deploy services on cloud and set up a private cloud environment (K3)
- Explain security challenges in cloud environment (K2)


# we should reduce the number of references (RSM)
** References
1. Kai Hwang, Geoffrey C Fox, Jack G Dongarra, ``Distributed and Cloud
   Computing, From Parallel Processing to the Internet of Things'',
   Morgan Kaufmann Publishers, 2012. (Units I, II, III, IV)
2. James E. Smith, Ravi Nair, ``Virtual Machines: Versatile Platforms
   for Systems and Processes'', Elsevier/Morgan Kaufmann, 2005. (Unit
   II)
3. Krutz, R. L., Vines, R. D, ``Cloud security. A Comprehensive Guide
   To Secure Cloud Computing'', Wiley Publishing, 2010. (Unit V)
4. Tim Mather, Subra Kumaraswamy, and Shahed Latif, ``Cloud Security
   and Privacy: an enterprise perspective on risks and compliance'',
   O'Reilly Media, Inc., 2009. (Unit V)
5. Danielle Ruest, Nelson Ruest, ``Virtualization: A Beginner's
   Guide'', McGraw-Hill Osborne Media, 2009.
6. Srinivasan A, Suresh J, ``Cloud Computing: A practical Approach for
   Learning and Implementation'', Pearson Education
   India, 2014. 

