* 
:properties:
:author: N Sujaudeen
:date: 12 May 2022
:end:

#+startup: showall
{{{title-tab}}}
| CODE | COURSE TITLE    | L | T | P | C |
|      | CLOUD COMPUTING | 2 | 0 | 2 | 3 |

** COURSE OBJECTIVES
- To understand the principles of Cloud Architecture, Models and Infrastructure.
- To understand the concepts of virtualization and virtual machines.
- To gain knowledge about virtualization Infrastructure.
- To explore and experiment various Cloud deployment environments.
- To learn about the security issues in the cloud environment. 

{{{unit}}}
| UNIT I | CLOUD ARCHITECTURE MODELS AND INFRASTRUCTURE | 6 |
Cloud Architecture: System Models for Distributed and Cloud Computing
-- NIST Cloud Computing Reference Architecture -- Cloud deployment
models -- Cloud service models; Cloud Infrastructure: Architectural
Design of Compute and Storage Clouds --  Design Challenges  
#+BEGIN_COMMENT
Layered Cloud Architecture Development -- Inter Cloud Resource Management --
Resource Provisioning and Platform Deployment -- Global Exchange of
Cloud Resources.
#+END_COMMENT
#+latex: % Unit III is from the course Cloud Computing IF7202, Anna University. M.E CSE - R2015 (NS)


{{{unit}}}
| UNIT II | VIRTUALIZATION BASICS| 6 |
#+BEGIN_COMMENT
Basics of Virtualization -- Emulation -- Interpretation -- Binary
Translation -- Virtualization Advantages --  Process Virtual Machines -- System
Virtual Machines
#+END_COMMENT
Virtual Machine Basics -- Taxonomy of Virtual Machines -- Hypervisor -- Key Concepts -- Virtualization
structure -- Implementation levels of virtualization -- Virtualization Types: Full Virtualization -- 
Para Virtualization -- Hardware Virtulization --  Virtualization of CPU, Memory and I/O devices.
#+latex: % Unit I is from the course Virtualization IF7020, Anna University. M.Tech IT- R2015 (NS)

{{{unit}}}
| UNIT III | VIRTUALIZATION INFRASTRUCTURE AND DOCKER | 7 |
Desktop Virtualization -- Network Virtualization -- Storage Virtualization -- System-level of Operating
Virtualization -- Application Virtualization -- Virtual clusters and Resource Management -- Containers vs. Virtual Machines --
Introduction to Docker -- Docker Components -- Docker Container -- Docker Images and Repositories.  

#+BEGIN_COMMENT
Virtual Machine Monitors: KVM, Xen, VMWareESXi server.
#+END_COMMENT
#+latex: % Unit II is from the course Virtualization IF7020, Anna University. M.Tech IT- R2015 (YVL)

{{{unit}}}
| UNIT IV | CLOUD DEPLOYMENT ENVIRONMENT | 6 |
Google App Engine -- Amazon AWS -- Microsoft Azure; Cloud Software
Environments -- Eucalyptus -- OpenStack.
#+BEGIN_COMMENT
-- OpenNebula -- CloudSim -- Removed Aneka
Unit IV is from the course Cloud Computing IF7202, Anna University. M.E CSE - R2015. 
Apache Hadoop is not  included here, as it will be covered in Big Data Analytics course. (YVL)
#+END_COMMENT

{{{unit}}}
| UNIT V | CLOUD SECURITY | 5 |
Virtualization System-Specific Attacks: Guest hopping -- VM migration attack -- hyperjacking.
Data Security and Storage; Identity and Access Management(IAM) - IAM Challenges - IAM Architecture and Practice.

#+BEGIN_COMMENT
Multi-tenancy Issues: Isolation of users/VMs from each other --
Virtualization System Vulnerabilities: Management console
vulnerabilities -- management server vulnerabilities -- administrative
VM vulnerabilities -- guest VM vulnerabilities, hypervisor
vulnerabilities -- hypervisor escape vulnerabilities -- configuration
issues;
#+END_COMMENT
#+latex: % As we changed entire Unit - V from AU syllabus, Unit V is from the course Cloud Security CC2005, SRM University. M.Tech in Cloud Computing. (YVL) 

\hfill *Total Periods: 45*

**  SUGGESTED EXERCISES

1. Install Virtualbox/VMware Workstation with different flavours of Linux or windows OS on top of windows7 or 8.
2. Install a C compiler in the virtual machine created using virtual box and execute Simple Programs
3. Install Google App Engine. Create hello world app and other simple web applications using python/java.
4. Use GAE launcher to launch the web applications.
5. Simulate a cloud scenario using CloudSim and run a scheduling algorithm that is not present in CloudSim.
6. Find a procedure to transfer the files from one virtual machine to another virtual machine.
7. Install Hadoop single node cluster and run simple applications like wordcount.
8. Creating and Executing Your First Container Using Docker.
9. Run a Container from Docker Hub

\hfill *Periods: 10*


** COURSE OUTCOMES 
After the completion of this course, students will be able to: 
1. Describe the design challenges in cloud (K2)
2. Apply the concept of virtualization and its types (K3)
3. Experiment with virtualization of hardware resources and Virtual Machine Monitors (K3)
4. Develop and deploy services on cloud and set up a private cloud environment (K3)
5. Explain security challenges in cloud environment (K2)


# we should reduce the number of references (RSM)
** REFERENCES
1. Kai Hwang, Geoffrey C Fox, Jack G Dongarra, ``Distributed and Cloud
   Computing, From Parallel Processing to the Internet of Things'',
   Morgan Kaufmann Publishers, 2012. (Units I, II, III, IV)
2. James E. Smith, Ravi Nair, ``Virtual Machines: Versatile Platforms
   for Systems and Processes'', Elsevier/Morgan Kaufmann, 2005. (Unit
   II)
3. James Turnbull, ``The Docker Book'', O'Reilly Publishers, 2014. (Unit
   III)
4. Krutz, R. L., Vines, R. D, ``Cloud security. A Comprehensive Guide
   To Secure Cloud Computing'', Wiley Publishing, 2010. (Unit V)
5. Tim Mather, Subra Kumaraswamy, and Shahed Latif, ``Cloud Security
   and Privacy: an enterprise perspective on risks and compliance'',
   O'Reilly Media, Inc., 2009. (Unit V)
6. Danielle Ruest, Nelson Ruest, ``Virtualization: A Beginner's
   Guide'', McGraw-Hill Osborne Media, 2009.
7. Srinivasan A, Suresh J, ``Cloud Computing: A practical Approach for
   Learning and Implementation'', Pearson Education
   India, 2014. 


