* 
:properties:
:author: Kanchana
:date: 12 May 2022
:end:

#+startup: showall
{{{title-tab}}}
| CODE | COURSE TITLE        | L | T | P | C |
|      | COGNITIVE COMPUTING | 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
- To understand foundations of cognitive computing
- To explore the role of AI, Big Data, Machine learning, NLP in cognitive systems
- To understand business implications of cognitive computing and develop solutions.

{{{unit}}}
| UNIT I | FOUNDATIONS OF COGNITIVE COMPUTING | 8 |
Cognitive computing as a new generation -- uses of cognitive systems -- gaining insights from data -- Artificial Intelligence as the foundation of cognitive computing -- understanding cognition; Design Principles for Cognitive Systems: Components of a cognitive system, building the corpus -- bringing data into a cognitive system -- machine learning -- hypotheses generation and scoring -- presentation and visualization services.

{{{unit}}}
| UNIT II | NLP IN SUPPORT OF A COGNITIVE SYSTEM | 8 |
Role of NLP in a cognitive system -- semantic web -- Applying natural language technologies to Business problems; Representing knowledge in Taxonomies and Ontologies: Knowledge representation -- Models for knowledge representation -- Implementation considerations.  

{{{unit}}}
| UNIT III | RELATIONSHIP BETWEEN BIG DATA AND COGNITIVE COMPUTING | 8 |
Dealing with human-generated data -- defining big data -- architectural foundation -- analytical data warehouses; Hadoop -- data in motion and streaming data; integration of big data with traditional data; Applying Advanced Analytics to cognitive computing:   Key capabilities in advanced analytics --  Impact of open source tools on advanced analytics. 

{{{unit}}}
| UNIT IV | BUSINESS IMPLICATIONS OF COGNITIVE COMPUTING  | 8 |
Preparing for a change -- advantages of new disruptive models --  comparison with a cognitive systems approach -- meshing data together differently -- using business knowledge to plan for the future --  answering business questions in new ways, building business specific solutions; Process of building a cognitive application: Emerging cognitive platform -- objective and the domain -- understanding the intended users and their attributes -- questions and exploring insights -- training and testing.

{{{unit}}}
| UNIT V | BUILDING A COGNITIVE HEALTH CARE APPLICATION | 8 |
Foundations of cognitive computing for healthcare -- constituents in healthcare ecosystem -- learning from patterns in healthcare Data -- cognitive applications across the healthcare eco system; Smarter cities: Cognitive Computing in Government -- smarter approaches to preventative healthcare -- building a smarter transportation infrastructure --  creating a cognitive community infrastructure -- next phase of cognitive cities 

\hfill *Total Periods: 45*

** COURSE OUTCOMES
Upon completion of this course, the students should be able to:
1. Explain how Artificial Intelligence, Machine Learning and Cognitive Computing are related and are used for application development (K2)
2. Describe Cognitive computing and NLP based techniques and models (K2)
3. Apply advanced analytics to cognitive computing (K3)
4. Apply technical and managerial issues in developing applications based on cognitive computing and Artificial Intelligence techniques. (K3)
5. Apply and assess cognitive computing and Artificial Intelligence Applications in an organizational setting (K3)

** REFERENCES
1. Judith H Hurwitz, Marcia Kaufman, Adrian Bowles , ``Cognitive computing and Big Data Analytics'' , Wiley, 2015 (Units 1, 2, 3, 4, and 5)
2. Pradeep Kumar Mallick, Samarjeet Borah, Emerging Trends and Applications in Cognitive Computing, IGI Global, 2018
3. Vishal Jain, Akash Tayal, Jaspreet Singh, Cognitive Computing Systems - Applications and Technological Advancements, Taylor & Francis, 2021 
4. Rob High , Tanmay Bakshi, Cognitive Computing with IBM Watson, Packt, 2019

