* <<<CP1236>>> BIO INFORMATICS
:properties:
:author: S. Kavitha
:date: 15 May 2022
:end:

#+startup: showall

{{{credits}}}
|L|T|P|C|
|3 |0|0|3 |


** COURSE OBJECTIVES
- To understand the concept and need of Bioinformatics 
- To transform biological data into knowledge and perform data analysis
- To learn machine learning algorithms for bioinformatics
- To learn hidden morkov modeling and probabilistic modeling 
- To know the importance of microarray data analysis


{{{unit}}}
|UNIT I | INTRODUCTION | 9 |
Introduction to Bioinformatics: Need for Bioinformatics technologies
-- Overview of Bioinformatics technologies; Overview of structural
bioinformatics: Organization of Structural bioinformatics -- Primary
resource: protein data bank -- Secondary resources and applications.

{{{unit}}}
| UNIT II | DATA WAREHOUSING AND DATA MINING IN BIOINFORMATICS | 9 |
Data warehousing in Bioinformatics: Bioinformatics data --
Transforming data to knowledge -- Data warehousing architecture --
Data quality; Data mining for Bioinformatics: Biomedical data analysis
-- DNA data analysis -- Protein data analysis.

{{{unit}}}
|UNIT III | MACHINE LEARNING IN BIOINFORMATICS | 9 |
Machine learning in Bioinformatics: Artificia Neural network -- Neural
network architecture and applications -- Genetic algorithm -- Fuzzy
system; Genome Analyses; Transcriptome Analyses.

#+begin_comment
two topics are included to apply and analyze ML alorithms
#+end_comment
 
{{{unit}}}
|UNIT IV | MODELING FOR BIOINFORMATICS | 9 |
Modeling for Bioinformatics: Hidden Markov modeling for biological
data analysis -- Comparative modeling -- Probabilistic modeling --
Molecular modeling.

{{{unit}}}
|UNIT V | MICROARRAY DATA ANALYSIS | 9 |
Microarray Data Analysis: Microarray technology for genome expression
study -- Image analysis for data extraction -- Data Analysis for
Pattern Discovery.

\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to
1. Explain the concept and need of bioinformatics (K2)
2. Identify genome, protein data and their equivalent storage and mining process (K3)
3. Apply machine learning algorithms on bioinformatics data (K3)
4. Apply Hidden Markov Modeling and probabilistic modeling for bioinformatics data (K3)
5. Infer the importance of microarray data analysis (K2)
   
** REFERENCES
1. Yi-Ping Phoebe Chen (Ed), ``BioInformatics Technologies'', First
   Indian Reprint, Springer Verlag, 2007 (Units 1, 2 3, 4, 5) 
2. Arthur M Lesk, ``Introduction to Bioinformatics'', Fourth Edition,
   Oxford University Press, 2008
3. Rui Jiang, Xuegong Zhang, Michael Q Zhang, ``Basics of
   Bioinformatics'', Tsinghua University Press, Springer, 2013
 
