* 
:properties:
:author: S V Jansi Rani
:date: 12 May 2022
:end:

#+startup: showall
{{{title-tab}}}
| CODE | COURSE TITLE            | L | T | P | C |
|      | SOCIAL NETWORK ANALYSIS | 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
- To understand the components of the social networks. 
- To execute the models and visualize the social network using tools. 
- To learn the mining of communities in the social network. 
- To study evolution of the social networks. 
- To know the applications of social networks in real time systems. 

{{{unit}}}
|UNIT I | INTRODUCTION 	|9| 
The Semantic Web: Limitations of current web -- Development of
semantic web -- Emergence of the social web; Statistical properties of
social networks; Social Network Analysis: Development of social
network analysis -- Key concepts and measures in network analysis --
Discussion; Blogs and online communities -- Web-based networks.


{{{unit}}} 
|UNIT II|MODELING AND VISUALIZATION |9| 
Modelling and aggregating social network data: Aggregating and
reasoning with social network data -- Advanced representations;
Visualization of Social Networks: Centrality -- Clustering --
Node-Edge diagrams; Visualizing online social networks: Node-Link
Diagrams -- Matrix-based representations

{{{unit}}} 
|UNIT III|MINING COMMUNITIES |9| 
Random walks in social networks and their applications: Random walks
on graphs -- Algorithms -- Applications; Detecting Communities in
Social Networks: Core methods -- Emerging fields and problems; Node
classification in social networks.

{{{unit}}} 
|UNIT IV| EVOLUTION OF SOCIAL NETWORKS  |9| 
Evolution in Social Networks: Framework -- Tracing  evolving
communities; Models and Algorithms for social influence analysis:
Influence related statistics -- Social similarity and influence --
Influence maximization in viral marketing; Algorithms and systems for
expert locations in social networks: Expert location without graph
constraints -- Score propagation -- Expert team formation; Link
Prediction in social networks: Feature based link prediction --
Bayesian probabilistic models -- Probabilistic relational models

{{{unit}}} 
|Unit V|Applications |9|
A learning based approach for real time emotion classification of
tweets; A new linguistic approach to assess the opinion of users in
social network environments; Explaining scientific and technical
emergence forecasting; Recommendation Systems.

\hfill *Total:45*

** Course Outcomes
After the completion of this course, students will be able to:  
- Explain the components of the social network(K2). 
- Make use of the tools, to  visualize the social network(K3). 
- Expalin the mining of communities in the social network(K2). 
- Utilize the models and algorithms to find the experts and links of the social network(K3). 
- Apply the social netwokring concepts in the various real time systems(K3). 

      
** References
1. Peter Mika, ``Social Networks and the Semantic Web'', Springer, 1st
   edition, 2007.
   edition, 2007. (Unit 1 - Chapter 1,2,3, Unit 2 -Chapter 5)
2. Borko Furht,``Handbook of Social Network Technologies and
   Applications'', Springer, 1st edition, 2011
   Applications'', Springer, 1st edition, 2011. ( Unit 2 - Chapter  27,28)
3. Charu C. Aggarwal, ``Social Network Data Analytics'', Springer,
   2014
   2014. (Unit 3 - Chapter 3 & 4, Unit 4 - Chapter 7, 8,9)
4. Przemyslaw Kazienko, Nitesh Chawla,``Applications of Social Media
   and Social Network Analysis'', Springer,2015
   and Social Network Analysis'', Springer,2015 (Unit 5)
5. Safia Kanwal;Sidra Nawaz;Muhammad Kamran Malik;Zubair Nawaz, ``A Review of Text-Based Recommendation Systems'',IEEE, 2021. (Unit 5)
6. Giles, Mark Smith, John Yen, ``Advances in Social Network Mining
   and Analysis'', Springer, 2010.
7. Guandong Xu , Yanchun Zhang and Lin Li, ``Web Mining and Social
   Networking – Techniques and applications'', Springer, 1st edition,
   2012
8. Ajith Abraham, Aboul Ella Hassanien, Vaclav Snasel, ``Computational
   Social Network Analysis: Trends, Tools and Research Advances'',
   Springer, 2012
