* 
:properties:
:author: Dr. V. S. Felix Enigo
:date: 12-05-2022
:end:

#+startup: showall
{{{title-tab}}}
** WIRELESS SENSOR NETWORKS    

| L | T | P | C |
| 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
- To study about the sensor node hardware and design principles.
- To study the functionalities of various MAC protocols for WSNs.
- To understand the working of data centric routing protocols in WSNs. 
- To understand the working of localization and topology control in WSNs. 
- To explore the various platforms and tools for WSN.

{{{unit}}}
|UNIT I | Introduction to Wireless Sensor Networks  | 9 |
Introduction: Challenges – Applications – Single node architecture: Hardware components – Energy consumption of sensor nodes – Network architecture: Sensor network scenarios – Optimization goals – Design principles – Service interfaces – gateway concepts.

{{{unit}}}
|UNIT II | Medium Access Control Layer  | 9 |
Fundamentals of  wireless MAC protocols –- Low duty cycle protocols and wakeup concepts -– Contention Based protocols -– Schedule-Based protocols -- The IEEE 802.15.4 MAC protocol.

{{{unit}}}
| UNIT III | Data Centric Routing | 9 |
Query processing –- Data aggregation -– Localized vs Centralized protocols -– Data gathering without memorizing links towards the sink -– Data dissemination from the sink -– Data gathering based on memorized broadcasting trees -– Periodic reports by all sensors -– Data gathering with data aggregation.

{{{unit}}}
| UNIT IV | LOCALIZATION AND TOPOLOGY CONTROL | 9 |
Localization and positioning : Properties of localization and positioning procedures -– Approaches -- Mathematical basics for the lateration problem -- Single-hop localization -- Positioning in multihop environments
Topology control: Concepts -- Controlling topology in flat networks -- Hierarchical networks by dominating sets -- Hierarchical networks by clustering -- Combining hierarchical topologies and power control.


{{{unit}}}
|UNIT V | SENSOR NETWORK PLATFORMS AND TOOLS | 9 |
Sensor Network Hardware:  Berkeley Motes -– Arduino IDE -– Node Level Software: Platforms -– Tiny OS -– Imperative Language -– nesC -– Simulators: NS–3, Contiki OS and COOJA IDE, TOSSIM -– State Centric Programming: PIECES. 


\hfill *Total Periods: 45*

** COURSE OUTCOMES
After completion of this course, the student will be able to:
1. Explain sensor node architecture and design principles. (K2)
2. Choose specific MAC protocols for the application. (K3)
3. Select data-centric routing based on application needs. ( k3)
4. Analyze the working of various localization and topology control techniques. (k4)
5. Explain various platforms and tools for WSN. (k2)

** REFERENCES
1. Holger Karl, Andreas Willig, “Protocols and Architectures for Wireless Sensor Networks”, John Wiley, 2005.  (unit – 1, 2, 4)
2. Ivan Stojmenovic, Handbook of Sensor Networks: Algorithms and Architectures,  Wiley Interscience, 2005. (unit 3)
3. Feng Zhao, Leonidas Guibas, “Wireless Sensor Networks”, Morgan Kaufmann, 2004  ( unit 5)


