* 
:properties:
:author: K. Lekshmi
:date: 12 May 2022
:end:

#+startup: showall
{{{title-tab}}}
| CODE | COURSE TITLE                  | L | T | P | C |
|      | IMAGE PROCESSING AND ANALYSIS | 2 | 0 | 2 | 3 |

** COURSE OBJECTIVES
- To understand basics of digital images
- To understand spatial and frequency domain processing
- To learn image segmentation techniques
- To learn feature detection and multi-resolution analysis
- To learn various applications of image processing.

{{{unit}}}
|UNIT I | FUNDAMENTALS OF IMAGE PROCESSING |5| 
Introduction -- Elements of visual perception -- Steps in Image
Processing Systems -- Image Acquisition -- Sampling and Quantization
-- Pixel Relationships -- Image Modalities -- File Formats; Image
Operations: Arithmetic -- Logical -- Statistical and Spatial operations.

{{{unit}}}
|UNIT II| IMAGE ENHANCEMENT AND RESTORATION |8| 
Spatial Domain processing: Filtering operations; Histograms; Smoothing
filters; Sharpening filters; Frequency Domain processing: Fourier Transform --
DFT and FFT; Filtering operations; Smoothing and Sharpening -- 
Selective filters; Homomorphic filtering; Restoration: Model of Image Degradation/Restoration Process, 
Noise Models -- Filters for noise removal in Spatial and Frequency domain.

#+BEGIN_COMMENT
Removal 
       Fuzzy techniques; Noise models; Filters for noise removal
Thought process  
       Having the idea of noise removal in spatial and frequency domain, students will be able to learn the concepts of the above
Rest of the Topics are re-ordered as Image Enhancement and Image Restoration in Spatial & Frequency Domain respectively
#+END_COMMENT

{{{unit}}}
|UNIT III| IMAGE SEGMENTATION |5| 
Thresholding techniques: Region growing -- splitting and merging -- Adaptive -- Otsu method;
Edge detection; Template matching; Gradient operation; Hysterisis Thresholding -- Canny operator -- Laplacian
operator; Image morphology -- Binary and Gray Level morphology
operations -- erosion; dilation -- opening-- closing operations --
Morphological watersheds.

#+BEGIN_COMMENT		
Removal 
       Features -- Corner and interest point detection -- 
	   boundary representation and detections -- texture descriptors -- 
	   regional descriptors and feature selection techniques;
Thought process  
        Removed as they will consume more time
	Image Segmentation can be a seperate topic and Featute related topics can be moved to Unit 4
#+END_COMMENT 

{{{unit}}}
|UNIT IV| FEATURE DETECTION AND MULTI RESOLUTION ANALYSIS  |6| 
Features -- Corner and interest point detection -- 
boundary representation and detections -- texture descriptors -- 
regional descriptors and feature selection techniques;
Multi Resolution Analysis: Image Pyramids -- Multi resolution
expansion -- Wavelet Transforms; Fast Wavelet transforms.

#+BEGIN_COMMENT	
Removal
		Image Compression: Fundamentals - Models - Error Free Compression -Lossy Compression -
		Compression Standards - Watermarking Color Images: Color Models; 
		Smoothing and Sharpening - Segmentation based on Color - Noise in Color Images
Inclusion 
       Features -- Corner and interest point detection -- 
	   boundary representation and detections -- texture descriptors -- 
	   regional descriptors and feature selection techniques;
Thought process  
        Removed as they will consume more time
#+END_COMMENT 

{{{unit}}}
|UNIT V| CASE STUDIES IN IMAGE PROCESSING|6|
Image Recognition: Fingerprint Recognition; Image Classification:
Tumor classification from Medical Images; Image Understanding: CBIR; 
Image Fusion: Statellite image enhancement; Object tracking: Surveillance applications.

\hfill *Total Periods: 30* 

** SUGGESTIVE LIST OF EXPERIMENTS:
1. Generate noisy images by adding Uniform, Gaussian, Salt and pepper noise to an input image. Observe the performance of smoothing filters in spatial domain.
2. Take a low contrast image and do the following:
	a) Generate a histogram of the image and observe how the intensity values are distributed
	b) Apply histogram equalization and matching
	c) Apply fuzzy sets for intensity transformation
3. Implement a program to perform a Fourier transform followed by the application of high pass filters and then retransform the data to show the filtered images. 
4. Implement a program to segment an image
	a) By calculating a threshold setting using the histogram of brightness values.
	b) Using adaptive thresholding
	c) Using watershed algorithm
5. Take a microscope cell image that has undergone a threshold operation. Perform the following morphological transform 
	a) erosion and dilation with a circular structuring element
	b) erosion and dilation with a square structuring element
	c) closing and opening with a cross shaped structuring element
6. Perform skeletonization on an input image which contains different shape objects. Observe the resultant images after 20, 30 and 40 iterations. 
7. Generate the edges of an image by applying the following edge detection operators: Roberts, Sobel, Prewitt, Laplacian and Canny operators.
8. Perform line, circle, ellipse detection using Hough transform for images.
9. Write a program to implement a discrete wavelet transform and its inverse for an image. (the user can decide the number of decomposition). Apply Daubechies, Haar  
   and Morlet.
10. Consider images of following characteristics:
	a) With features of varying sizes
	b) With features of varying sizes that are not convex
	c) With a series of lines of approximately the same length
	d) With features with different numbers of internal holes.
     Develop a program to count the features, label the pixels with a unique identifying number, measure the area, total perimeter for the images.

\hfill *Total Periods: 15*

** COURSE OUTCOMES
After the completion of this course, students will be able to:
1. Explain the fundamental concepts of a digital image processing system (K2)
2. Apply image enhancement and restoration techniques in spatial and frequency domains (K3)
3. Make use of image segmentation techniques for object detection (K3) 
4. Analyze the multi resolution methods and image transforms for color images (K4)
5. Apply techniques of object enhancement, detection, recognition, and classification in various applications (K3)

#+BEGIN_COMMENT 
- Design and implement enhancement and segmentation algorithms for image processing application. (K4)
- Perform analysis using various image features. (K3)
- Analyze the multi resolution techniques and methods used for images. (K3)
- Make a positive professional contribution in the field of Digital Image Processing. (K4)
#+END_COMMENT 

** REFERENCES
1. Rafael C.Gonzalez, Richard E.Woods, ``Digital Image Processing'',
   Fourth Edition, Pearson Education, 2018. (Units I, II, III, IV)
2. Wilhelm Burger, Mark J. Burge, ``Principles of Digital Image Processing : Core Algorithms'', Springer, 2009. (Units V)
3. Anil K.Jain, ``Fundamentals of Digital Image Processing'',
   PHI, 2006.
4. Rafael C.Gonzalez, Richard E.Woods, Eddins, ``Digital Image
   Processing Using MATLAB'', Second Edition, Tata McGraw-Hill, 2009.
5. Davis, E. R. ``Machine Vision'' Second Edition, 1997.

#+BEGIN_COMMENT 
1. Rafael C.Gonzalez, Richard E.Woods, ``Digital Image Processing'',
   Third Edition, Pearson Education, 2008. (Units I, II, III, IV)
2. Anil K.Jain, ``Fundamentals of Digital Image Processing'',
   PHI, 2006.
3. Rafael C.Gonzalez, Richard E.Woods, Eddins, ``Digital Image
   Processing Using MATLAB'', Second Edition, Tata McGraw-Hill, 2009.
4. Davis, E. R. ``Machine Vision'' Second Edition, 1997.
#+END_COMMENT 



