* <<<CP1233>>> IMAGE PROCESSING AND ANALYSIS
:properties:
:author: K. Lekshmi
:date: 12 May 2022
:end:

#+startup: showall

{{{credits}}}
|L|T|P|C|
|2|0|2|3|

** Course Objectives
- To understand basics of digital images
- To understand spatial and frequency domain processing
- To learn image segmentation techniques
- To learn feature detection and multi-resolution analysis
- To learn various applications of image processing.

{{{unit}}}
|Unit I | Fundamentals of Image Processing |5| 
Introduction -- Elements of visual perception -- Steps in Image
Processing Systems -- Image Acquisition -- Sampling and Quantization
-- Pixel Relationships -- Image Modalities -- File Formats; Image
Operations: Arithmetic -- Logical -- Statistical and Spatial operations.

{{{unit}}}
|Unit II| Image Enhancement and Restoration |8| 
Spatial Domain processing: Filtering operations; Histograms; Smoothing
filters; Sharpening filters; Frequency Domain processing: Fourier Transform --
DFT and FFT; Filtering operations; Smoothing and Sharpening -- 
Selective filters; Homomorphic filtering; Restoration: Model of Image Degradation/Restoration Process, 
Noise Models -- Filters for noise removal in Spatial and Frequency domain.

#+BEGIN_COMMENT
Removal 
       Fuzzy techniques; Noise models; Filters for noise removal
Thought process  
       Having the idea of noise removal in spatial and frequency domain, students will be able to learn the concepts of the above
Rest of the Topics are re-ordered as Image Enhancement and Image Restoration in Spatial & Frequency Domain respectively
#+END_COMMENT

{{{unit}}}
|Unit III| Image Segmentation |5| 
Thresholding techniques: Region growing -- splitting and merging -- Adaptive -- Otsu method;
Edge detection; Template matching; Gradient operation; Hysterisis Thresholding -- Canny operator -- Laplacian
operator; Image morphology -- Binary and Gray Level morphology
operations -- erosion; dilation -- opening-- closing operations --
Morphological watersheds.

#+BEGIN_COMMENT		
Removal 
       Features -- Corner and interest point detection -- 
	   boundary representation and detections -- texture descriptors -- 
	   regional descriptors and feature selection techniques;
Thought process  
        Removed as they will consume more time
	Image Segmentation can be a seperate topic and Featute related topics can be moved to Unit 4
#+END_COMMENT 

{{{unit}}}
|Unit IV| Feature Detection and Multi Resolution Analysis  |6| 
Features -- Corner and interest point detection -- 
boundary representation and detections -- texture descriptors -- 
regional descriptors and feature selection techniques;
Multi Resolution Analysis: Image Pyramids -- Multi resolution
expansion -- Wavelet Transforms; Fast Wavelet transforms.

#+BEGIN_COMMENT	
Removal
		Image Compression: Fundamentals - Models - Error Free Compression -Lossy Compression -
		Compression Standards - Watermarking Color Images: Color Models; 
		Smoothing and Sharpening - Segmentation based on Color - Noise in Color Images
Inclusion 
       Features -- Corner and interest point detection -- 
	   boundary representation and detections -- texture descriptors -- 
	   regional descriptors and feature selection techniques;
Thought process  
        Removed as they will consume more time
#+END_COMMENT 

{{{unit}}}
|Unit V| Case Studies in Image Processing|6|
Image Recognition: Fingerprint Recognition; Image Classification:
Tumor classification from Medical Images; Image Understanding: CBIR; 
Image Fusion: Statellite image enhancement; Object tracking: Surveillance applications.

\hfill *Total: 30* 

** List of Experiments:
1.	Program to implement smoothing or averaging filter in spatial domain.
2.	Image Processing on Histogram Processing
	- Program to find histogram value and display histograph of a grayscale and color image.
	- Program to obtain histogram equalization image
3.	Image Processing on Fourier Transformation
	- Program to discretize an image using Fourier transformation.
	- Program to eliminate the high frequency components of an image.
4.	Program to fill the region of interest for the image.
5.	Image Processing on Segmentation
	- Program for morphological operation: erosion and dilation
	- Program for segmentation of an image using watershed transforms.
6.	Program to determine the edge detection of an image using different operators.
7.	Program to perform discrete wavelet transform on image.

\hfill *Total: 15*

** Course Outcomes
After the completion of this course, students will be able to:
- Explain the fundamental concepts of a digital image processing system (K2)
- Apply image enhancement and restoration techniques in spatial and frequency domains (K3)
- Make use of image segmentation techniques for object detection (K3) 
- Analyze the multi resolution methods and image transforms for color images (K4)
- Apply techniques of object enhancement, detection, recognition, and classification in various applications (K3)

#+BEGIN_COMMENT 
- Design and implement enhancement and segmentation algorithms for image processing application. (K4)
- Perform analysis using various image features. (K3)
- Analyze the multi resolution techniques and methods used for images. (K3)
- Make a positive professional contribution in the field of Digital Image Processing. (K4)
#+END_COMMENT 

      
** References
1. Rafael C.Gonzalez, Richard E.Woods, ``Digital Image Processing'',
   Fourth Edition, Pearson Education, 2018. (Units I, II, III, IV)
2. Wilhelm Burger, Mark J. Burge, ``Principles of Digital Image Processing : Core Algorithms'', Springer, 2009. (Units V)
3. Anil K.Jain, ``Fundamentals of Digital Image Processing'',
   PHI, 2006.
4. Rafael C.Gonzalez, Richard E.Woods, Eddins, ``Digital Image
   Processing Using MATLAB'', Second Edition, Tata McGraw-Hill, 2009.
5. Davis, E. R. ``Machine Vision'' Second Edition, 1997.

#+BEGIN_COMMENT 
1. Rafael C.Gonzalez, Richard E.Woods, ``Digital Image Processing'',
   Third Edition, Pearson Education, 2008. (Units I, II, III, IV)
2. Anil K.Jain, ``Fundamentals of Digital Image Processing'',
   PHI, 2006.
3. Rafael C.Gonzalez, Richard E.Woods, Eddins, ``Digital Image
   Processing Using MATLAB'', Second Edition, Tata McGraw-Hill, 2009.
4. Davis, E. R. ``Machine Vision'' Second Edition, 1997.
#+END_COMMENT 



