* 
:properties:
:author: S.Rajalakshmi, R Kanchana
:date: 
:end:

#+startup: showall
{{{title-tab}}}
| CODE | COURSE TITLE           | L | T | P | C |
|      | FUNCTIONAL PROGRAMMING | 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
1. To write small to medium-sized functional programs for a
   variety of applications
2. To exploit a variety of programming techniques typical in
   functional programming such as use of recursion, modelling
   with recursive datatypes, abstraction and reuse with the
   help of higher order functions and monads
3. To appreciate the strengths and possible weaknesses of the
   functional programming paradigm

{{{unit}}}
| UNIT I | FUNCTIONS | 9 |
Functions and functional programming -- Sessions and scripts
-- Types and classes -- Defining functions.

{{{unit}}}
|UNIT II | LISTS, RECURSION, HIGHER-ORDER FUNCTIONS | 9 |
Lists -- List comprehensions -- Recursive functions -- Higher order
functions.

{{{unit}}}
|UNIT III | TYPES, CLASSES | 9 |
Declaring types and classes -- Interactive programming.
  
{{{unit}}}
| UNIT IV | MONADS | 9 |
Monads -- Monadic Parsing -- Foldables -- Traversables.
  
{{{unit}}}
|UNIT V | LAZY EVALUATION | 9 |
Lazy evaluations -- Infinite objects -- Pascal's triangle,
digits of a number, sieve of Eratosthenes -- Reasoning about
programs.
 
\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to
1. Write programs in a functional style
2. Use lists, recursion, and higher order functions
3. Apply polymorphism and higher-order functions
4. Separate stateful functions using monads
5. Ue infinite data structures and reason formally about
   functional programs
  
** REFERENCES
1. Richard Bird, ``Introduction to Functional Programming using Haskell'',
   second edition, Prentice-Hall International, 1998.
2. Graham Hutton, ``Programming in Haskell'', second edition,
   Cambridge University Press, 2016.



