*  
:properties:
:author:
:date:
:end:

#+startup: showall
{{{title-tab}}}
| CODE | COURSE TITLE                      | L | T | P | C |
|      | SOFTWARE CONFIGURATION MANAGEMENT | 3 | 0 | 0 | 3 |

** R2021 CHANGES :noexport:
1. A new syllabus

** COURSE OBJECTIVES
- Explain and demonstrate the key aspects of traditional configuration management
- Understand and demonstrate the microservices   
- Explore and deploy microservices in a container 
- Install and explore networking services
- Modify configuration techniques using kubernetes and Docker swarm 



{{{unit}}}
|UNIT I | MICROSERVICES | 9 |
An Introduction to Microservices:What Are Microservices? ; Switching to Microservices:Cost Components; Interprocess Communication:Putting It All Together; Case Study: Migration to Microservices -- Planning for Migration -- Applying Microservices Criteria -- Converting to Microservices -- Application Build and Deployment.

#+begin_comment
...Included from Text Book 2, chapter 1,2,3,12

#+end_comment
 
{{{unit}}}
|UNIT II | CONTAINERS | 9 |
Docker Containers:Virtual Machines -- Containers -- Docker Architecture and Components -- The Power of Docker: A Simple Example;
Docker Interface:Key Docker Commands -- Dockerfile -- Docker Compose; Case Study: Containerizing a
Helpdesk Application : Containerizing Microservices -- Deploying the Catalog Microservice.

#+begin_comment
...Included from Text Book 2, chapter 5.7.13
#+end_comment
 

{{{unit}}}
|UNIT III | NETWORKING AND DISCOVERY | 9 |

Docker Networking: Bridge Mode Networking -- Host Mode Networking -- Container Mode Networking -- No Networking -- Wrapping It Up; Service Discovery ;  Service Registry.

#+begin_comment
...Included from Text Book 3, chapter   2, 4
...Included from Text Book 2, chapter  9  
#+end_comment

{{{unit}}}
|UNIT IV | ORCHESTRATION  | 9 |
Container Orchestration : Kubernetes -- Kubectl -- Master Node -- Worker Nodes -- Kubernetes Cluster;  Docker Swarm : Nodes -- Services -- Task -- Example: Swarm Cluster.
{{{unit}}}

|UNIT V | Google Cloud Paltform | 9 |
Get Started with Google Cloud Platform (GCP) : Get Started with Google Cloud Platform (GCP) -- Understanding GCP Projects -- Creating a Project -- Create a VM Instance -- Delete a Project; Understanding Cloud Shell : Using Cloud Shell -- Deploy a VM Instance Using Cloud Shell -- Work with Projects in Cloud Shell -- Cloud Shell Editor; Google Cloud SDK : Secure and Manage Your GCP Account -- Multi-Factor Authentication -- Create an Account with Specific Roles.


#+begin_comment
...Included from Text book (1), chapter 6,8,10  
...Included from Text book (2) chapter 11
#+end_comment
#+begin_comment
...Included from Text Book 2, chapter 9 
#+end_comment

** COURSE OUTCOMES
Upon completion of the course, the student should be able to
1.  
2. Develop  and deploy microservices (K3)
3. Build a container and deploy a  microservice (K3)
4. Explain networking concepts in containers (K2)
5. Choose  configuration features using Kubernetes and Docker swarm (K3).

      
** REFERENCES
1. Shirley Lacy and David Norfolk, ``CONFIGURATION MANAGEMENT, Expert
   guidance for IT service managers and practitioners``, Revised
   edition, BCS Learning and Development Ltd, UK, 2014. (Unit 1)
2. Parminder Singh Kocher Boston, ``Microservices and Containers'',
   Addison-Wesley, 2018. (Unit 1,2,3,4)
3. Michael Hausenblas, ``Docker Networking and Service Discovery'',
   O'Reilly Publication, 2016. (Unit 3)
4. Getting Started with Containers in Google Cloud Platform - Deploy, Manage, and Secure Containerized
   Applications, Shimon Ifrah, Apress Publication 2021. (Unit - 5)
5. Thomas Uphill, ``Mastering Puppet'', Second Edition,PACKT
   Publishing, 2016
6. Scott Coulton, ``Puppet for Containerization'', PACKT Publishing,
   2016
7. Cesar de la Torre, Bill Wagner, Mike Rouses, ``.NET Microservices:
   Architecture for Containerized .NET Applications'', Microsoft
   Corporation, V5.) Edition, 2020. 
   
