* 
:properties:
:author: S V Jansi Rani, N Sujaudeen
:date: 27 June 2018
:end:

#+startup: showall
{{{title-tab}}}
| CODE | COURSE TITLE              | L | T | P | C |
|      | SOFTWARE DEFINED NETWORKS | 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
- To learn the concepts and basics of SDN, and Openflow.
- To demonstrate SDN Controller and programming with SDN.
- To learn virtualization of data center and network functions .
- To study about Network Topology & SDN Framework.
- To investigate various use cases using  SDN. 

{{{unit}}}
|UNIT I |SDN  PLANE SEPARATION & OPENFLOW|9| 
Separation of Control Plane and Data Plane -- Distributed and
centralized control plane -- OpenFlow protocol -- Hybrid Approaches.

{{{unit}}}
|UNIT II| SDN CONTROLLER AND PROGRAMMING SDN |9| 
SDN Controller: General Concepts -- Layer3 Centric -- Plexi --
CiscoOnePK ; Programming in SDN : The Management Interface --
Application-Network Divide -- Modern Orchestration ; Programmable Data Planes.

{{{unit}}}
|UNIT III|DATA CENTER & NETWORK FUNCTION VIRTUALIZATION|9| 
Data Center: Multitenant Data Center -- Virtualised Multitenant Data
Center -- SDN solution for Data Center -- VLAN -- NVGRE; Network
Function Virtualization: Virtualization and Data Plane I/O - Service
Locations and Chaining - NFV at ETSI and Non-ETSI.


{{{unit}}}
|UNIT IV| NETWORK TOPOLOGY & SDN FRAMEWORK |9| 
Network Topology: Traditional methods, LLDP, BGP - TE/LS, ALTO, I2RS
Topology; SDN Framework: Juniper SDN framework -- IETF SDN Frameworks
-- Open Daylight Controller Framework.

{{{unit}}}
|UNIT V|USE CASES|9|
Use cases for bandwidth scheduling -- manipulation and calendaring --
Use Cases for Data Center Overlays -- Big Data -- and Network Function
Virtualization -- Input traffic classification and triggered actions

\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
1. Explain the concepts, basics of SDN and Openflow(K2)
2. Explain SDN Controller and programming with SDN(K2)
3. Analyse various SDN solutions for data center and about Network Function Virtualization.(K4)
4. Make use of SDN Framework(K3)
5. Analyse various use cases in implementing SDN(K4)
      
** REFERENCES
1. Thomas D. Nadeau, ``SDN: Software Defined Networks, An
   Authoritative Review of Network Programmability Technologies'',
   First Edition, Ken Gray Publisher: O'Reilly Media, 2013. (Unit 1 - Chapters 1,2 and 3; Unit 2 - Chapters 4,5; Unit 3 - Chapters 6,7; Unit 4 - Chapters 8,9; Unit 5 - Chapters 10,11 and 12)
2. Silvano Gai, ``Building a Future-Proof Cloud Infrastructure: A Unified Architecture for Network, Security, and Storage Services'',  O'Reilly Media, 2020.  3. Paul Goransson and Chuck Black, ``Software Defined Networks: A
   Comprehensive Approach'', Morgan Kaufmann, 2014.
4. Vivek Tiwari, ``SDN and OpenFlow for Beginners'' Amazon
   Digital Services, Inc.,  2013.
5. Fei Hu, ``Network Innovation through OpenFlow and SDN: Principles
   and Design'', CRC Press, 2014.
